In [2]:
import util as u

In [3]:
def fix(numObj, digits=1):
    return f"{numObj:.{digits}f}"


df =u.read_file("momentum")
df = df[["count",
         "alpha",
         "run",
         "name",
         "res_point",
         "result_err",
         "delta_time",
         "math_iters"]]

na_df = df[df["result_err"].isna()]
val_total_math_iter = int(na_df[na_df["count"] == 10]["math_iters"].mean() / 1000)
df.insert(
    loc= len(df.columns),
    column='math_per_oper',
    value=[val_total_math_iter for i in range(df.shape[0])])
# print(df.head(8).to_latex(
#     formatters={"res_point" : lambda x: [float(fix(i, 1)) for i in x]}))
df.head()

,count,alpha,run,name,res_point,result_err,delta_time,math_iters,math_per_oper
0,10,0.00010,1001,momentum,"[4.530598195087703, 0.647839540073381]",NaN,0.282242,8000,8
1,10,0.00050,1001,momentum,"[2.049593706729165, 0.9933564898213896]",NaN,0.202106,8000,8
2,10,0.00075,953,momentum,"[2.0050159693214615, 0.9992722135419256]",0.000099,0.231020,7616,8
3,10,0.00100,706,momentum,"[2.0050444155194187, 0.999292962671122]",0.000100,0.170661,5640,8
4,10,0.00125,578,momentum,"[2.0049952610636526, 0.9992685097247208]",0.000098,0.137802,4616,8

In [4]:
#get_alpha(df)
df["alpha"].unique()

array([0.0001 , 0.0005 , 0.00075, 0.001  , 0.00125, 0.0025 , 0.005  ,
       0.02   ])

In [5]:
df.groupby('alpha')['result_err'].apply(lambda x: x.isna().sum())

alpha
0.00010    19
0.00050     4
0.00075     3
0.00100     0
0.00125     4
0.00250    16
0.00500    20
0.02000    28
Name: result_err, dtype: int64

In [6]:
df[df["result_err"].isna()].head(50)

,count,alpha,run,name,res_point,result_err,delta_time,math_iters,math_per_oper
0,10,0.00010,1001,momentum,"[4.530598195087703, 0.647839540073381]",NaN,0.282242,8000,8
1,10,0.00050,1001,momentum,"[2.049593706729165, 0.9933564898213896]",NaN,0.202106,8000,8
7,10,0.02000,1001,momentum,"[1.2895610176325096e+101, 1.679791019354654e+102]",NaN,0.239690,8000,8
8,10,0.00010,1001,momentum,"[-2.9371468927415436, 1.7010435336400211]",NaN,0.324253,8000,8
9,10,0.00050,1001,momentum,"[1.9054681061864898, 1.0117543407379586]",NaN,0.201658,8000,8
10,10,0.00075,1001,momentum,"[1.9924083249475317, 1.0010122596110178]",NaN,0.240727,8000,8
15,10,0.02000,1001,momentum,"[1.1640093973038583e+80, -3.6833817663157066e+80]",NaN,0.229956,8000,8
16,10,0.00010,1001,momentum,"[5.569691219880187, 0.4778410544274828]",NaN,0.215234,8000,8
17,10,0.00050,1001,momentum,"[2.0713638193724453, 0.9902678152721476]",NaN,0.257093,8000,8
18,10,0.00075,1001,momentum,"[2.005191976389434, 0.9992536658121289]",NaN,0.302745,8000,8
23,10,0.02000,1001,momentum,"[4.562427369148881e+93, 2.2046913410669623e+94]",NaN,0.281722,8000,8
24,10,0.00010,1001,momentum,"[-1.866205998505642, 1.524623996336936]",NaN,0.216570,8000,8
25,10,0.00050,1001,momentum,"[1.9171462698196922, 1.012065780788873]",NaN,0.221900,8000,8
26,10,0.00075,1001,momentum,"[1.9945380214769348, 1.0007794855225187]",NaN,0.219675,8000,8
31,10,0.02000,1001,momentum,"[4.0629905747369135e+89, -9.481443406718258e+88]",NaN,0.254035,8000,8
32,40,0.00010,1001,momentum,"[2.694803020160501, 0.8884180556799426]",NaN,0.604075,8000,8
39,40,0.02000,1001,momentum,None,NaN,0.643071,8000,8
40,40,0.00010,1001,momentum,"[0.5595589297979701, 1.234772069814503]",NaN,0.611231,8000,8
47,40,0.02000,1001,momentum,None,NaN,0.620552,8000,8
48,40,0.00010,1001,momentum,"[3.035910352338604, 0.8255283623210793]",NaN,0.654756,8000,8
55,40,0.02000,1001,momentum,None,NaN,0.594217,8000,8
56,40,0.00010,1001,momentum,"[0.9487931911752069, 1.1692124483180102]",NaN,0.655141,8000,8
63,40,0.02000,1001,momentum,None,NaN,0.682868,8000,8
64,70,0.00010,1001,momentum,"[2.250971465947652, 0.9639337612427902]",NaN,0.986341,8000,8
70,70,0.00500,1001,momentum,None,NaN,1.289034,8000,8
71,70,0.02000,1001,momentum,None,NaN,1.225951,8000,8
72,70,0.00010,1001,momentum,"[1.4887857360600125, 1.0734626859970013]",NaN,1.259591,8000,8
78,70,0.00500,1001,momentum,None,NaN,0.993205,8000,8
79,70,0.02000,1001,momentum,None,NaN,0.958924,8000,8
80,70,0.00010,1001,momentum,"[2.3724339279566182, 0.9463961140099861]",NaN,0.939768,8000,8
86,70,0.00500,1001,momentum,None,NaN,0.976694,8000,8
87,70,0.02000,1001,momentum,None,NaN,1.080258,8000,8
88,70,0.00010,1001,momentum,"[1.6005662636551024, 1.0586863489098173]",NaN,1.047731,8000,8
94,70,0.00500,1001,momentum,None,NaN,1.004696,8000,8
95,70,0.02000,1001,momentum,None,NaN,1.173596,8000,8
96,100,0.00010,1001,momentum,"[2.011776556550034, 0.9981921413731082]",NaN,1.806180,8000,8
101,100,0.00250,1001,momentum,"[2.256127807717864e+271, 1.3916879060241905e+272]",NaN,1.676904,8000,8
102,100,0.00500,1001,momentum,None,NaN,1.616107,8000,8
103,100,0.02000,1001,momentum,None,NaN,1.651168,8000,8
104,100,0.00010,1001,momentum,"[1.9770246453405067, 1.0034096841337667]",NaN,1.585391,8000,8
109,100,0.00250,1001,momentum,"[9.125163473254081e+273, 5.519267191825421e+274]",NaN,1.505900,8000,8
110,100,0.00500,1001,momentum,None,NaN,1.609375,8000,8
111,100,0.02000,1001,momentum,None,NaN,1.602612,8000,8
112,100,0.00010,1001,momentum,"[2.0170676048759515, 0.9974752494458735]",NaN,1.496320,8000,8
117,100,0.00250,1001,momentum,"[-1.5229910919613436e+273, -1.1215004332971e+274]",NaN,1.607518,8000,8
118,100,0.00500,1001,momentum,None,NaN,1.770430,8000,8
119,100,0.02000,1001,momentum,None,NaN,1.629925,8000,8
120,100,0.00010,1001,momentum,"[1.9813136352019227, 1.002815628963174]",NaN,1.666666,8000,8
125,100,0.00250,1001,momentum,"[-3.6717185416122e+268, -1.9683587158564205e+269]",NaN,1.658257,8000,8
126,100,0.00500,1001,momentum,None,NaN,1.620158,8000,8

In [45]:
print(df.groupby('alpha')['result_err'].apply(lambda x: x.isna().sum())\
.to_latex())

\begin{tabular}{lr}
\toprule
 & result_err \\
alpha &  \\
\midrule
0.000100 & 19 \\
\bottomrule
\end{tabular}

In [31]:
df_na = df.dropna()

In [3]:
df.groupby(['count', 'alpha'])['run'].apply(lambda x: x.mean())

count  alpha
10     0.00010    1001.00
       0.00050    1001.00
       0.00075     989.00
       0.00100     749.00
       0.00125     598.75
       0.00250     284.25
       0.00500     128.00
       0.02000    1001.00
40     0.00010    1001.00
       0.00050     690.75
       0.00075     447.75
       0.00100     330.00
       0.00125     256.75
       0.00250      99.75
       0.00500     193.00
       0.02000    1001.00
70     0.00010    1001.00
       0.00050     475.00
       0.00075     302.75
       0.00100     217.00
       0.00125     162.50
       0.00250     320.25
       0.00500    1001.00
       0.02000    1001.00
100    0.00010    1001.00
       0.00050     236.75
       0.00075     139.00
       0.00100      93.25
       0.00125      93.50
       0.00250    1001.00
       0.00500    1001.00
       0.02000    1001.00
130    0.00010     992.25
       0.00050     166.50
       0.00075      93.75
       0.00100      92.25
       0.00125     105.50
       0.00250    1001.00
       0.00500    1001.00
       0.02000    1001.00
160    0.00010     870.75
       0.00050     133.25
       0.00075      93.25
       0.00100      99.00
       0.00125     128.00
       0.00250    1001.00
       0.00500    1001.00
       0.02000    1001.00
190    0.00010     840.75
       0.00050     128.50
       0.00075      97.75
       0.00100     434.50
       0.00125    1001.00
       0.00250    1001.00
       0.00500    1001.00
       0.02000    1001.00
Name: run, dtype: float64

In [33]:
print(
    df_na.groupby(['count', 'alpha'])['run']
    .apply(lambda x: x.mean()).to_latex(float_format="{:.1f}".format))

\begin{tabular}{llr}
\toprule
 &  & run \\
count & alpha &  \\
\midrule
\multirow[t]{2}{*}{10} & 0.002500 & 667.8 \\
 & 0.005000 & 322.8 \\
\cline{1-3}
\multirow[t]{5}{*}{40} & 0.000500 & 726.5 \\
 & 0.000750 & 476.2 \\
 & 0.001000 & 343.5 \\
 & 0.001250 & 273.0 \\
 & 0.002500 & 103.2 \\
\cline{1-3}
\multirow[t]{5}{*}{70} & 0.000500 & 355.8 \\
 & 0.000750 & 219.8 \\
 & 0.001000 & 150.8 \\
 & 0.001250 & 105.0 \\
 & 0.002500 & 101.0 \\
\cline{1-3}
\multirow[t]{4}{*}{100} & 0.000500 & 208.2 \\
 & 0.000750 & 120.2 \\
 & 0.001000 & 94.5 \\
 & 0.001250 & 92.8 \\
\cline{1-3}
\multirow[t]{4}{*}{130} & 0.000500 & 196.2 \\
 & 0.000750 & 111.5 \\
 & 0.001000 & 100.0 \\
 & 0.001250 & 103.0 \\
\cline{1-3}
\multirow[t]{5}{*}{160} & 0.000100 & 788.0 \\
 & 0.000500 & 115.5 \\
 & 0.000750 & 92.0 \\
 & 0.001000 & 90.2 \\
 & 0.001250 & 122.2 \\
\cline{1-3}
\multirow[t]{4}{*}{190} & 0.000100 & 694.0 \\
 & 0.000500 & 89.8 \\
 & 0.000750 & 90.2 \\
 & 0.001000 & 114.5 \\
\cline{1-3}
\bottomrule
\end{tabular}